### ISSUE TITLE
Last issue i'll make. Create a custom data type

### ISSUE THREAD

**Issue by koreaneggroll** [midnqp/lib-cpython-builtins#19]
Create a custom data type that can be an int double float or string at the same time. Give it a go.

**Comment by midnqp** [comment]
Honestly I think it is the easiest to build.
The interface would be:
```c
libcpb_obj string(char const *str) {
    ...
    return string.val;
}
```
You are talking about `libcpb_obj`, which at the same time may be a list, int, dict, string.... I will work on it, and add that workaround to this repo -- if God wills.

**Comment by koreaneggroll** [comment]
No, i'll give u this: typedef, extern, struct. That will work.

**Comment by midnqp** [comment]
> No, i'll give u this: typedef, extern, struct. That will work.

That's exactly how I'll create the `libcpb_obj`.

**Comment by midnqp** [comment]
`typedef` is optional. `extern` is for header files. You'll only need a `struct`.

```c
struct string {
	char *str;
	size_t len;
};
void str_init(struct string *string) {
	string->len = 0;
	string->str = new(char*, 1);
	strcpy(string->str, "");
}
```
I actually implemented this a long ago. Just couldn't have the time to inform.

I used this project as a dependency to [Chat@Terminal](github.com/midnqp/terminal.chat).
